[package]
name = "chessire"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "chessire-bin"
path = "src/bin.rs"


[dependencies]
termion = "*"
